# Generated by Django 4.2.30 on 2026-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('A/C', 'A/C'), ('Non A/C', 'Non A/C')], max_length=20)),
                ('sharing_type', models.CharField(choices=[('2 Sharing', '2 Sharing'), ('3 Sharing', '3 Sharing'), ('4 Sharing', '4 Sharing')], max_length=20)),
                ('total_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
