# Generated by Django 4.2.30 on 2026-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_beds',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
