# Generated by Django 4.2.30 on 2026-07-22 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar', models.CharField(max_length=12)),
                ('college', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Left', 'Left')], default='Active', max_length=20)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.bed')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
            ],
        ),
    ]
