# Generated by Django 4.2.30 on 2026-07-26 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=150, verbose_name='College / Workplace'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('late_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cheque', 'Cheque')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('collected_by', models.CharField(default='Admin', max_length=100)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Paid', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='hostel.student')),
            ],
        ),
    ]
