# Generated by Django 4.2.30 on 2026-07-26 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_room_available_beds_alter_student_college_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=20)),
                ('breakfast_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lunch_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dinner_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='hostel.student')),
            ],
        ),
    ]
