# Generated by Django 4.2.30 on 2026-07-27 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Wi-Fi', 'Wi-Fi'), ('Gas', 'Gas'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Salary', 'Salary'), ('Food Purchase', 'Food Purchase'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], max_length=30)),
                ('paid_to', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
